name: witt
description: Simple state management powered by ValueNotifier with service locator.
version: 2.0.2
repository: https://github.com/weaze-id/witt

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
